condense_wildcard_suffixes = true
edition = "2018"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_indent = "Visual"
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
trailing_semicolon = false
use_try_shorthand = true
wrap_comments = true
unstable_features = true

[width_heuristics]
fn_call_width = 60
attr_fn_like_width = 70
struct_lit_width = 40
struct_variant_width = 40
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
